# 프로미스

> 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 `콜백 함수`를 사용한다.<br>
> 하지만 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동기 처리 중 발생한 에러의 처치가 곤란하며,<br> 여러 개의 비동기 처리를 한번에 처리하는 데도 한계가 있기 때문에 `프로미스`가 등장하였다.<br>

- 프로미스는 콜백패턴이 가진 단점을 보완하며, `비동기 처리 시점을 명확하게 표현`할 수 있다는 장점이 있다.

## \* 비동기 처리를 위한 콜백 패턴의 단점

### ✔️ 콜백 헬

![콜백헬](https://github.com/hyeonseok98/js-deep-dive-study/assets/166012944/9f4e8bba-4d05-461b-a94c-e34b5ba695a5)


- 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다.

```jsx
let g = 0;

setTimeout(() => {
  g = 100;
}, 0);
console.log(g); // 0
```

### ✔️ 비동기함수란?

-> 함수 내부에 비동기로 동작하는 코드를 포함한 함수.

- 위처럼 비동기 함수 내부의 비동기로 동작하는 코드에서 `처리 결과를 외부로 반환`하거나 `상위 스코프의 변수에 할당`하면 기대한 대로 동작하지 않는다.

- 이처럼 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 `비동기 함수가 비동기 처리결과를 가지고 또 다시 비동기 함수를 호출`하여 복잡해지는 현상을 `콜백 헬`이라 한다.

### ✔️ 에러 처리의 한계

- 비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것이다.

```jsx
try {
  setTimeout(() => {
    throw new Error("error");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다.
  console.log(error);
}
```

### ✔️ 프로미스의 생성

- Promise는 ECMAScript 사양에 정의된 표준 빌트인 객체다.
- Promise 생성자 함수는 비동기 처리를 수행할 콜백함수를 인수로 전달받는데 이 콜백함수는 `resolve`와 `reject` 함수를 인수로 전달받는다.

```jsx
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if(비동기 처리 성공){
    resolve('result')
  } else {
    reject('failure reason')
  }
})
```

- 비동기 처리가 성공하면 resolve 함수를 호출하고 비동기 처리가 실패하면 reject 함수를 호출한다.<br>
  -> 이처럼 프로미스 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.

---

<br>

## 비동기 작업이 가질 수 있는 3가지 상태

### 1. Pending(대기 상태) -> 프로미스가 생성된 직후 기본상태

### 2. Fulfilled(성공) -> resolve 함수 호출

### 3. Rejected(실패) -> reject 함수 호출

- Pending 상태에서 Fulfilled로 해결이 되었을 때는 `reslove` 가 된 것이고
- Pending상태에서 Rejected상태로 거부 되었을 때는 `reject` 된 것이다.
  - 이처럼 프로미스 상태는 resolve 또는 reject 함수를 호출하는 것이다.
- settled 상태 : fulfilled / resected 상태와 상관없이 pending 이 아닌 상태로 비동기 처리가 수행된 상태를 말한다.
- 프로미스는 pending 상태에서 fulfilled 또는 rejected 상태, 즉 settled 로 상태로 변화할 수 있다.

### ✔️ Promise

- 어떤 함수가 Promise를 반환한다는 것은 `그 함수는 비동기적으로 동작`을 하고 반환한 Promise객체를 이용해서 비동기 처리의 결과 값을 then과 catch로 이용하겠다는 의미이다.

<br>

## \* 프로미스의 후속 처리 메서드

### ✔️ Promise.prototype`.then`

- then 메서드는 두 개의 콜백 함수를 인수로 전달받는다.

- `첫번째 콜백` 함수: 프로미스가 `fulfilled` 상태가 되면 호출되고 프로미스의 비동기 처리 결과를 인수로 전달받는다.
- `두번째 콜백` 함수: 프로미스가 `rejected` 상태가 되면 호출되고 프로미스의 에러를 인수로 전달받는다.
- `then` 메서드는 언제나 프로미스를 반환한다.

### ✔️ Promise.prototype`.catch`

- catch 메서드의 콜백함수는 프로미스가 `rejected` 상태인 경우만 호출된다.

### ✔️ Promise.prototype`.finally`

- finally 메서드의 콜백 함수는 프로미스의 성공 혹은 실패와 상관없이 `무조건 한 번 호출`된다.

<br>

### ✔️ 프로미스의 에러 처리

- catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러 뿐만 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.
- catch 메서드를 사용하는 것이 또한 가독성이 좋고 명확하다.

<br>

### ✔️ 프로미스 체이닝

- then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다.
  -> 이를 프로미스 체이닝이라 한다.

> 프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다.<br> 다만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.

-> 콜백 패턴은 가독성이 좋지 않은데 이 문제는 `async/await`를 통해 해결할 수 있다.
async/await를 사용하면 `프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 구현`할 수 있다.

```jsx
const url = "https://jsonplaceholder.typicode.com";

promiseGet(`${url}/posts/1`)
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

<br>

## \* 프로미스의 정적 메서드

### ✔️ Promise.resolve / Promise.reject

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

- Promise.resolve 메서드는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

- Promise.reject 메서드는 인수로 전달받은 값을 reject하는 프로미스를 생성한다.

```jsx
// 배열을 resolve/reject 하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1,2,3]);
const rejectedPromise = Promise.reject(new Error('Error'));

// 위와 동일함
const resolvedPromise = new Promise(resolve => resolve([1,2,3]);
const rejectedPromise = new Promise((_,reject) => reject(new Error('Error'));
```

### ✔️ Promise.all

- 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1,2,3]
  .catch(console.error);
```

### ✔️ Promise.race

- Promise.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
- Promise.all 처럼 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

```jsx
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // 1
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)), // 2
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)), // 3
])
  .then(console.log) // 3
  .catch(console.error);
```

프로미스가 rejected 상태가 되면 Promise.all 메서드와 동일하게 처리된다.

즉, Promise.race 메서드에 전달된 프로미스가 하나라도 rejected 상태가 되면 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

```jsx
Promise.race([
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 1")), 3000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 2")), 2000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 3")), 1000)
  ),
])
  .then(console.log)
  .catch(console.error); // Error: Error 3
```

### ✔️ Promise.allSettled

- Promise.allSettled 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
- 전달받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환한다.
  - Promise.allSettled 메서드가 반환한 배열에는 fulfilled 또는 rejected 상태와는 상관없이
  - Promise.allSettled 메서드가 인수로 전달받은 모든 프로미스들의 처리 결과가 모두 담겨 있다.

```jsx
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>  setTimeout(() => reject(new Error("Error!")), 1000)),
]).then(console.log);

/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <annymous>:3:54}
]
*/

[
  // 프로미스가 fulfilled 상태인 경우
  {status: "fulfilled", value: 1},
  // 프로미스가 rejected 상태인 경우
  {status: "rejected", reason: Error: Error! at <annymous>:3:60}
]
```

## \* 마이크로태스트 큐

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

- 위 예제의 출력 순서는 2 -> 3 -> 1 이다.
- 그 이유는 프로미스의 후속 처리 메서드의 콜백 함수는 `태스크 큐가 아니라 마이크로태스크 큐에 저장`되기 때문이다.
- 마이크로태스크 큐는 태스큐 큐와는 별도의 큐다.
- 마이크로태스크 큐에는 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다. 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.
- 콜백 함수나 이벤트 핸들러를 일시 저장한다는 점에서 태스크 큐와 동일하지만 마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.
- 즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다. 이후 마이크로 태크스 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

## \* fetch

- fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.

- fetch 함수는 XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

- fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

```jsx
const promise = fetch(url, [, options]);
```

- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.
- fetch 함수에 첫 번째 인수로 HTTP 요청을 전송할 URL만 전달하면 GET 요청을 전송한다.

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1").then((response) =>
  console.log(response)
);
```

- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 프로미스를 반환하므로 후속 처리 메서드 then을 통해 프로미스가 resolve한 Response 객체를 전달받을 수 있다.

- Response 객체는 HTTP 응답은 나타내는 다양한 프로퍼티를 제공한다.

- Response.prototype에는 Response 객체에 포함되어 있는 HTTP 응답 몸체를 위한 다양한 메서드를 제공한다. <br>
  예를 들어, fetch 함수가 반환한 프로미스가 래핑하고 있는 MIME 타입이 application/json인 HTTP 응답 몸체를 취득하려면 Response.prototype.json 메서드를 사용한다.
- Response.prototype.json 메서드는 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1")
  // response는 HTTP응답을 나타내는 Response 객체다.
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then((response) => response.json())
  // json은 역직렬화된 HTTP 응답 몸체다.
  .then((json) => console.log(json));
// {userId: 1, id: 1, title: "delectus aut autem". completed: false}
```

- fetch 함수를 사용할 때는 에러 처리에 주의해야 한다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongURL)
  .then(() => console.log("ok"))
  .catch(() => console.log("error"));
```

- 부적절한 URL이 지정 되었기 때문에 404 Not Found 에러가 발행하고 catch 후속 처리 메서드에 의해 'error'가 출력될 것처럼 보이지만 'ok'가 출력된다.

<br>

> fetch 함수가 반환하는 프로미스는 기본적으로 404 Not Found 나 500 Internal Server Error 와 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다.<br> 오프라인 등의 네트워크 장애나 CORS 에러로 의해 요청이 완료되지 못한 경우에만 프로미스를 reject한다.<br>
> <br>
> -> fetch 함수를 사용할 때는 다음과 같이 fetch 함수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리할 필요가 있다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongURL)
  // response는 HTTP 응답을 나타내는 Response 객체다.
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.log(err));
```

